[tools]
go = "latest"
node = "22"
deno = "2.0.0"
ruby = "3.4.4"
# java = "openjdk-23.0.0"
[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
ruby_build_opts = "CC=gcc-14 CXX=g++-14"
